# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and TestNG

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Ставим JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3.
      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      # 4.
      - name: Run Tests
        run: mvn test

      # 5.
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-surefire-reports
          path: target/surefire-reports/

      # 6.
      - name: Upload TestNG HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-html-report
          path: target/test-output/



